[package]
name = "afplay"
version = "0.1.0"
edition = "2018"
description = "Audio playback library"
authors = ["Eduard Müller <mail@emuell.net>"]
exclude = ["assets", "examples"]
categories = ["audio", "synth", "music", "gamedev"]

[dependencies]
log = { version = "^0.4", features = ["max_level_debug", "release_max_level_info"] }
lazy_static = { version = "1.4.0" }
crossbeam-channel = { version = "0.5" }
crossbeam-queue = { version = "0.3.6" }
audio_thread_priority = { version = "^0.26", default-features = false, features = ["winapi"] }
rubato = { version = "0.12.0" }
rb = { version = "^0.4" }
symphonia = { version = "^0.5", features = [ "aac", "alac", "mp3", "isomp4" ] }
dasp = { version = "0.11.0", features = [ "signal" ], optional = true }
fundsp = { version = "0.9.0", optional = true }
cubeb = { version = "0.10.1", optional = true }
cpal = { version = "^0.14", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.39.0", features = ["Win32_System_Com"], optional = true }

[dev-dependencies]
device_query = { version = "1.1.1" }
ctrlc = { version = "3.2.3" }

[profile.release]
# enable debug info in release builds for profiling
debug = 1

[profile.dev.package.rubato]
# rubato is very slow in debug builds without optimization  
opt-level = 3

[features]
cpal-output = ["cpal"]
cubeb-output = ["cubeb", "windows"]
dasp-synth = ["dasp"]
fundsp-synth = ["fundsp"]
default = ["cpal-output", "dasp-synth", "fundsp-synth"]

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "play-file"
[[example]]
name = "play-synth"
required-features = ["dasp-synth", "fundsp-synth"]
[[example]]
name = "play-interactive"
required-features = ["dasp-synth"]
