[package]
name = "afplay"
version = "0.1.0"
edition = "2018"
description = "Audio playback library"
authors = ["Eduard Müller <mail@emuell.net>"]
exclude = ["assets", "examples"]
categories = ["audio", "synth", "music", "gamedev"]

[dependencies]
log = { version = "^0.4", features = ["max_level_debug", "release_max_level_info"] }
lazy_static = { version = "^1.4" }
crossbeam-channel = { version = "^0.5" }
crossbeam-queue = { version = "^0.3" }
dashmap = { version = "^5.4" }
sort = { version = "^0.8" }
audio_thread_priority = { version = "^0.26", default-features = false, features = ["winapi"] }
rubato = { version = "^0.12" }
rb = { version = "^0.4" }
symphonia = { version = "^0.5", features = [ "aac", "alac", "mp3", "isomp4" ] }
assert_no_alloc = {version = "^1.1", optional = true }
dasp = { version = "^0.11", features = [ "signal" ], optional = true }
fundsp = { version = "^0.13", optional = true }
cubeb = { version = "^0.10", optional = true }
cpal = { version = "^0.15", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "^0.48", features = ["Win32_System_Com"], optional = true }

[dev-dependencies]
device_query = { version = "^1.1" }
ctrlc = { version = "^3.2" }

[profile.release]
debug = 1 # debug info for profiling

# enable optimization for a few DSP packages that are else extremely slow in debug builds
[profile.dev.package.rubato]
opt-level = 2
[profile.dev.package.rustfft]
opt-level = 2
[profile.dev.package.realfft]
opt-level = 2

[features]
assert-no-alloc = ["assert_no_alloc"]
cpal-output = ["cpal"]
cubeb-output = ["cubeb", "windows"]
dasp-synth = ["dasp"]
fundsp-synth = ["fundsp"]
default = ["cpal-output", "dasp-synth", "fundsp-synth"]

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "play-file"
[[example]]
name = "play-synth"
required-features = ["dasp-synth", "fundsp-synth"]
[[example]]
name = "play-interactive"
required-features = ["dasp-synth"]
