[package]
name = "afstream"
version = "0.1.0"
edition = "2018"
authors = ["emuell"]
exclude = ["assets", "examples"]
categories = ["audio", "playback"]

[dependencies]
string-error = "^0.1"
log = { version = "^0.4", features = ["max_level_debug", "release_max_level_info"] }
crossbeam-channel = { version = "0.5" }
crossbeam-queue = { version = "0.3.6" }
audio_thread_priority = { version = "^0.26", default-features = false, features = ["winapi"] }
libsamplerate = { version = "^0.1" }
rb = { version = "^0.4" }
symphonia = { version = "^0.5", features = [ "aac", "alac", "mp3", "isomp4" ] }
cubeb = { version = "0.10.1", optional = true }
cpal = { version = "^0.14", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.39.0", features = ["Win32_System_Com"] }

[features]
# default = ["cubeb"]
default = ["cpal"]
