[package]
name = "afplay"
version = "0.1.0"
edition = "2018"
description = "A cross-platform audio playback library"
authors = ["Eduard Müller <mail@emuell.net>"]
exclude = ["assets", "examples"]
categories = ["audio", "playback", "games", "sounds"]

[dependencies]
log = { version = "^0.4", features = ["max_level_debug", "release_max_level_info"] }
crossbeam-channel = { version = "0.5" }
crossbeam-queue = { version = "0.3.6" }
audio_thread_priority = { version = "^0.26", default-features = false, features = ["winapi"] }
libsamplerate = { version = "^0.1" }
rb = { version = "^0.4" }
symphonia = { version = "^0.5", features = [ "aac", "alac", "mp3", "isomp4" ] }
dasp = { version = "0.11.0", features = [ "signal" ], optional = true }
cubeb = { version = "0.10.1", optional = true }
cpal = { version = "^0.14", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.39.0", features = ["Win32_System_Com"] }

[features]
default = ["cpal", "dasp"]

[[example]]
name = "play-synth"
required-features = ["dasp"]
[[example]]
name = "play-file"
